[workspace]
members = [
    "crabstd",
    "drivers/fs/initrd",
    "drivers/storage/ram",
    "kernel", "kernel_loader", "kernel_shared",
    "multiboot",
    "x86_64",
]
resolver = "2"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true
